
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-16
owner: ucsb-cs156-f25
repo_name: team02-f25-16
pull_requests: [{"author":{"id":"U_kgDOCM8WGw","is_bot":false,"login":"wpleee","name":"William Lee"},"headRefName":"wpleee-MenuItemReview-form","number":65,"title":"Form Component for MenuItemReview plus tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/65"},{"author":{"id":"U_kgDOCM8WGw","is_bot":false,"login":"wpleee","name":"William Lee"},"headRefName":"wpleee-MenuItemReview-fixtures","number":64,"title":"Created fixtures for MenuItemReview","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/64"},{"author":{"id":"U_kgDOC31Aag","is_bot":false,"login":"alexjh2","name":""},"headRefName":"aj-UCSBDiningCommonsMenuItems-fixtures","number":63,"title":"Aj ucsb dining commons menu items fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/63"},{"author":{"id":"U_kgDOCM8WGw","is_bot":false,"login":"wpleee","name":"William Lee"},"headRefName":"wpleee-MenuItemReview-backend","number":62,"title":"Copy files for Backend CRUD API MenuItemReview from team02","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/62"},{"author":{"id":"U_kgDOC31Aag","is_bot":false,"login":"alexjh2","name":""},"headRefName":"aj-UCSBDiningCommonsMenuItem-backend","number":61,"title":"aj - copy backend CRUD operations from team01 for the menuitems table","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/61"}]
