
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-16
owner: ucsb-cs156-f25
repo_name: team02-f25-16
pull_requests: [{"author":{"id":"U_kgDOBmEn_g","is_bot":false,"login":"mihir-s-05","name":""},"headRefName":"mihir-s-05-end2end-tests","number":130,"title":"created end to end tests for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/130"},{"author":{"id":"U_kgDOBmEn_g","is_bot":false,"login":"mihir-s-05","name":""},"headRefName":"mihir-s-05-integration-tests","number":127,"title":"Created integration tests for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/127"}]
