
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-16
owner: ucsb-cs156-f25
repo_name: team02-f25-16
pull_requests: [{"author":{"id":"U_kgDOCBQ7GQ","is_bot":false,"login":"Saqif-Ayaan","name":""},"headRefName":"saqif-edit-recommendationRequest-page","number":117,"title":"Added Edit Page Functionality to Recommendation Requests","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/117"},{"author":{"id":"MDQ6VXNlcjQyNTIxODgw","is_bot":false,"login":"omar882","name":"Omar Aboutaleb"},"headRefName":"omar882-help-request-table","number":116,"title":"HelpRequest Table","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/116"},{"author":{"id":"MDQ6VXNlcjQyNTIxODgw","is_bot":false,"login":"omar882","name":"Omar Aboutaleb"},"headRefName":"omar882-create-help-requests-page2","number":108,"title":"Added Create page for HelpRequests","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/108"},{"author":{"id":"U_kgDOCBQ7GQ","is_bot":false,"login":"Saqif-Ayaan","name":""},"headRefName":"saqif-create-recommendationRequest-page","number":107,"title":"Created Create Page for Recommendation Requests","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/107"}]
