
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-16
owner: ucsb-cs156-f25
repo_name: team02-f25-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjQyNTIxODgw","is_bot":false,"login":"omar882","name":"Omar Aboutaleb"},"headRefName":"omar882-help-requests-integration-tests","number":141,"title":"Added Integration tests for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/141"},{"author":{"id":"U_kgDOBnO7gw","is_bot":false,"login":"quinnkos","name":"Quinn Koster"},"headRefName":"quinn-end2end-tests","number":140,"title":"Quinn end2end tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/140"},{"author":{"id":"U_kgDOBnO7gw","is_bot":false,"login":"quinnkos","name":"Quinn Koster"},"headRefName":"quinn-integration-tests","number":139,"title":"add integration test for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/139"},{"author":{"id":"U_kgDOCM8WGw","is_bot":false,"login":"wpleee","name":"William Lee"},"headRefName":"wpleee-endtoendtest","number":136,"title":"End 2 End Tests for MenuItemReview","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/136"},{"author":{"id":"U_kgDOBmEn_g","is_bot":false,"login":"mihir-s-05","name":""},"headRefName":"mihir-s-05-end2end-tests","number":130,"title":"created end to end tests for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/130"}]
