
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-16
owner: ucsb-cs156-f25
repo_name: team02-f25-16
pull_requests: [{"author":{"id":"U_kgDOC31Aag","is_bot":false,"login":"alexjh2","name":""},"headRefName":"aj-menuitems-e2e-tests","number":144,"title":"Aj menuitems e2e tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/144"},{"author":{"id":"MDQ6VXNlcjQyNTIxODgw","is_bot":false,"login":"omar882","name":"Omar Aboutaleb"},"headRefName":"omar882-help-requests-end-to-end-tests","number":143,"title":"Added end to end tests for HelpRequests","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/143"},{"author":{"id":"U_kgDOC31Aag","is_bot":false,"login":"alexjh2","name":""},"headRefName":"aj-menuitems-integration-tests","number":142,"title":"aj - add integration tests for menuitems Controller endpoints","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/142"},{"author":{"id":"MDQ6VXNlcjQyNTIxODgw","is_bot":false,"login":"omar882","name":"Omar Aboutaleb"},"headRefName":"omar882-help-requests-integration-tests","number":141,"title":"Added Integration tests for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/141"},{"author":{"id":"U_kgDOBnO7gw","is_bot":false,"login":"quinnkos","name":"Quinn Koster"},"headRefName":"quinn-end2end-tests","number":140,"title":"Quinn end2end tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-16/pull/140"}]
